# Generated by Django 4.0.4 on 2022-05-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_job_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='length',
            field=models.CharField(choices=[('less then 6 month', 'Less then 6 month'), ('more then 6 month', 'More then 6 month')], default='less then 6 month', max_length=20),
        ),
    ]
