# Generated by Django 4.0.4 on 2022-05-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_job_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='length',
            field=models.CharField(choices=[('Less Then 6 Month', 'Less Then 6 Month'), ('More Then 6 Month', 'More Then 6 Month')], default='less then 6 month', max_length=20),
        ),
    ]
